[package]
name = "functions-api"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
functions-core = { path = "../functions-core" }

[build-dependencies]
cbindgen = "0.28.0"